workspace/modulo_03/crypto_wallet/config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins #declara 7 rotas de uma vez só para utilizar o CRUD

  root to: 'welcome#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

workspace/modulo_03/crypto_wallet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

workspace/modulo_03/crypto_wallet/app/models/coin.rb
class Coin < ApplicationRecord
end

workspace/modulo_03/crypto_wallet/app/models/mining_type.rb
class MiningType < ApplicationRecord
end

workspace/modulo_03/crypto_wallet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

workspace/modulo_03/crypto_wallet/app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout "adm"
  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy!

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

workspace/modulo_03/crypto_wallet/app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy!

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:name, :acronym)
    end
end

workspace/modulo_03/crypto_wallet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end

workspace/modulo_03/crypto_wallet/app/helpers/application_helper.rb
module ApplicationHelper
    def date_br(date_us)
        date_us.strftime("%d/%m/%Y")
    end
    
    def name_application
        "Crypto Wallet App" 
    end
    
    def ambiente_rails
        if Rails.env.development?
            "desenvolvimento"
        elsif Rails.env.production?
            "produção"
        else
            "Teste"
        end
    end

end

workspace/modulo_03/crypto_wallet/app/helpers/coins_helper.rb
module CoinsHelper
end

workspace/modulo_03/crypto_wallet/app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

workspace/modulo_03/crypto_wallet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

workspace/modulo_03/crypto_wallet/app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">

  


</div>

workspace/modulo_03/crypto_wallet/app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
    <%#= image_tag coin.url_image, width:30, height:30 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

workspace/modulo_03/crypto_wallet/app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

workspace/modulo_03/crypto_wallet/app/views/coins/index.html.erb
<p style="color: green" id="notice"><%= notice %></p>

<h1>Coins</h1>

<table>
  <thread>
      <tr>
        <th>Description</th>
        <th>Acronym</th>
        <th>Image</th>
      </tr>
  </thread>
  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, size: "30x30" %></td>
        <td><%= link_to 'show', coin %></td>
        <td><%= link_to 'edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'delete', coin, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>

workspace/modulo_03/crypto_wallet/app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

workspace/modulo_03/crypto_wallet/app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<p> 
  <strong> Description: </strong>
  <%= @coin.description %>
</p>

<p>
  <strong> acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong> img </strong>
  <%= image_tag @coin.url_image, size: "30x30" %>
</p>

<div>
  <%= link_to "Edit this coin", edit_coin_path(@coin) %> |
  <%= link_to "Back to coins", coins_path %>

  <%= button_to "Destroy this coin", @coin, method: :delete %>
</div>

workspace/modulo_03/crypto_wallet/app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1> Cabeçalho - ADM </h1>
    </header>
    <%= yield %> 

    <footer>
      <p> Desenvolvido por <strong>Derek Barragão</strong> </p>
    </footer>
  </body>
</html>

workspace/modulo_03/crypto_wallet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1> Cabeçalho </h1>
    </header>
    <%= yield %>

    <footer>
      <p> Desenvolvido por <strong>Derek Barragão</strong> </p>
    </footer>
  </body>
</html>

workspace/modulo_03/crypto_wallet/app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

workspace/modulo_03/crypto_wallet/app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong>Name:</strong>
    <%= mining_type.name %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

workspace/modulo_03/crypto_wallet/app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

workspace/modulo_03/crypto_wallet/app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to "Show this mining type", mining_type %>
    </p>
  <% end %>
</div>

<%= link_to "New mining type", new_mining_type_path %>

workspace/modulo_03/crypto_wallet/app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

workspace/modulo_03/crypto_wallet/app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete %>
</div>

workspace/modulo_03/crypto_wallet/app/views/welcome/_menu.html.erb
<ul>
    <li>
        <%= link_to "Cadastro de Moedas", coins_path %>
    </li>
    <li>
        <%= link_to "Cadastro tipo de mineração", mining_types_path %>
    </li>
    
</ul>

workspace/modulo_03/crypto_wallet/app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo!</h1>

<%= render "menu" %> <%# UTILIZANDO UMA PARTIAL para renderizar o menu%>

<p><%= name_application %> </p>

<p>Derek Barragão</p>

<p> A soma é: <%= 1 + 1 %> </p>
<p> Seu nome de tras pra frente é: <%= "derek".reverse %> </p>

<% ax = "wooow" %>
<p>minha variavel ax é: <%= ax %></p>

<p>A data de hoje é: <%= date_br(Date.today) %></p>

<%#= esse é um comentario %>

<p>
    voce esta em ambiente de <%= Rails.env %>
</p>

<p>
    nome do ambiente utilizando helper <%= ambiente_rails %>
</p>

<p>Eu sou uma variavevl de instancia/sessão recebida na url: <%=@meu_nome%></p>
<p> Meu curso é um curso de: <%= @curso %> </p>